"""initial migration

Revision ID: 196a591c7789
Revises:
Create Date: 2026-04-12 00:24:44.451866

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "196a591c7789"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "encomendas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cliente", sa.String(), nullable=False),
        sa.Column("data", sa.DateTime(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("valor_sinal", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_encomendas_cliente"), "encomendas", ["cliente"], unique=False
    )
    op.create_index(
        op.f("ix_encomendas_status"), "encomendas", ["status"], unique=False
    )
    op.create_table(
        "produtos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nome", sa.String(), nullable=False),
        sa.Column("preco", sa.Float(), nullable=False),
        sa.Column("estoque", sa.Integer(), nullable=False),
        sa.Column("criado_em", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_produtos_nome"), "produtos", ["nome"], unique=False)
    op.create_table(
        "itens_encomenda",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("encomenda_id", sa.Integer(), nullable=False),
        sa.Column("produto_id", sa.Integer(), nullable=False),
        sa.Column("quantidade", sa.Integer(), nullable=False),
        sa.Column("preco_unitario", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["encomenda_id"],
            ["encomendas.id"],
        ),
        sa.ForeignKeyConstraint(
            ["produto_id"],
            ["produtos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_itens_encomenda_encomenda_id"),
        "itens_encomenda",
        ["encomenda_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_itens_encomenda_produto_id"),
        "itens_encomenda",
        ["produto_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_itens_encomenda_produto_id"), table_name="itens_encomenda")
    op.drop_index(op.f("ix_itens_encomenda_encomenda_id"), table_name="itens_encomenda")
    op.drop_table("itens_encomenda")
    op.drop_index(op.f("ix_produtos_nome"), table_name="produtos")
    op.drop_table("produtos")
    op.drop_index(op.f("ix_encomendas_status"), table_name="encomendas")
    op.drop_index(op.f("ix_encomendas_cliente"), table_name="encomendas")
    op.drop_table("encomendas")
    # ### end Alembic commands ###
